### ISSUE TITLE
All Trade Balances Not Showing

### ISSUE THREAD

**Issue by Cryptonic2** [tulihub/PT-MoonBot#11]
Hello, not sure if it's because all the kinks for the newly added ETH market support haven't been worked out yet or not, but MoonBot is showing all positions except for 2. 

The "Profit Trailer BAL" information at the bottom of the Summary section is all correct, but the "Current Balance" just above is showing 0.35 ETH short of what is actually "in trade". Specifically, NEO and DGD are the 2 positions that have been DCA'ed that are not showing up in the total. They are also not showing up in the "Binance" toggle, but they do show up in the "DCA" toggle.

Any ideas?

**Comment by Cryptonic2** [comment]
- Update

After NEO DCA'ed once it seems it is now showing up in the MoonBot. Only DGD and that balance is missing now. Seems like this is something that should fix itself eventually?

**Comment by tulihub** [comment]
is that specific coin you didnt see have an amount of >= 1 ?
are those coins you trade with ETH? or they were bought with other Market trade?

**Comment by Cryptonic2** [comment]
My base market is ETH, correct. Right now the amount of DGD the bot owns is 0.5. Is there a way to allow coin investments under 1 to be shown as well?

It seems to make more sense now. Was the over 1 requirement to have moonbot not include dust?

**Comment by tulihub** [comment]
Exactly, its for the "dust" thing. otherwise you would see many irrelevant coins.

And yes, there is a way to set the minimum for a coin, or default for all.
see "crumbs" at https://github.com/tulihub/PT-MoonBot/wiki/application.properties#others.

For example, add to application.properties:
`crumbs.dgd = 0.4`

Reading the application.properties page is highly recommended ^^
